- Client/src/Actions/FilterParamActions.ts
- Client/src/Components/AttributeFilter/SingleFieldFilter.jsx
- Client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts
- Client/src/Views/Question/Params/FilterParamNew/State.ts
Also patch SingleFieldFilter to properly be null in the intermetiate state of no data
I have question rendering as a dropdown with user dataset IDs at the top,  with the filter params at the bottom depending on the user dataset.
It didn't work after changing the user dataset because there was stale state: activeOntologyTerm referred to the filter for a previous dataset.
Now after the user dataset changes, the filter params starts "afresh", and is usable.
After this change and a rebuild, the UI starts to work on wbazant.microbiomedb.org - I can give you  credentials for a prepared QA account that has good data for testing if you want to see the change in action. **Not tested anywhere else** and this is my first change to WDKClient so I don't have a great overview of the codebase. Needs …
> Update activeOntologyTerm after acting on dependent param change

- Client/src/Components/CheckboxTree/CheckboxTreeNode.tsx
Otherwise React spends a long time processing them all upfront.
The functionality is still not ideal when there are very many of nodes representing e.g. distinct species in a taxonomic tree, but with this change it at least happens after opening the relevant checkbox, instead of later. 
This can happen for user datasets, because people can upload whatever they want, but also on the live site in searches for taxon abundance.
> Only render the CheckboxTreeNode children if the node is visible and expanded

- Client/src/StoreModules/QuestionStoreModule.ts
Things changed:
1) extractRealParamValues wasn't working correctly for filter params.
It couldn't make a desired initial state of filters, `"{"filters":[]}"` when providing param.biom_dataset=17298 in the URL:
```
makeDefaultParamValues(question.parameters)
{biom_dataset: "17321", samples_filter_metadata_user: "{"filters":[]}"}
extractRealParamValues(question.parameters, initialParamData)
{biom_dataset: "17298", samples_filter_metadata_user: ""}
```
"" is not a valid state of filters, because it's not valid JSON. There
was an error in the call to JSON.parse in FilterParamUtils.getFilters.
2) getQuestionGivenParameters was only called when there's a step
params from URL (initialParamData) also need this call.
Otherwise, the question object retrieved is wrong when there are
dependent …
> QuestionStoreModule can handle params specified in a URL

- Client/src/Components/Overlays/Dialog.css
- Client/src/StoreModules/UnhandledErrorStoreModule.ts
This fixes two issues:
1. Dialogs covering the error modal.
2. Infinite loop when `submitError` throws.
> Error handling fixes

- Client/src/Controllers/StrategyWorkspaceController.tsx
- Client/src/Views/Strategy/UnownedStrategy.tsx
This pull request introduces a message to the user when they try to access a strategy that they do not own. It is not know if the strategy actually exists, so the message has to support multiple possibilities.
This behavior can be seen at https://dfalke-b.plasmodb.org/plasmo.dfalke/app/workspace/strategies/123456789
> Show message to user when attempting to access an unowned strategy

- Client/src/Views/ResultTableSummaryView/BasketCell.tsx
- Client/src/Views/ResultTableSummaryView/BasketHeading.tsx
- Client/src/Views/ResultTableSummaryView/BasketIconButton.tsx
- Client/src/Views/ResultTableSummaryView/ResultTable.tsx
- Client/src/Views/ResultTableSummaryView/ResultTableSummaryView.scss
This relates to a UX issue, detailed in https://trello.com/c/KsMCALB8.
----
* Remove basket column heading
* Make download and basket actions look like buttons
* Add icons to download, basket, and add columns buttons
> Result table basket buttons

- Client/src/Components/AttributeFilter/MembershipField.jsx
- Client/src/Components/Mesa/Ui/MesaController.jsx
- Client/src/Components/Mesa/Ui/PaginationMenu.jsx
- Client/src/Components/Mesa/style/Ui/Pagination.scss
- Client/src/Views/Question/Params/FilterParamNew/FilterParamNew.tsx
- Client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts
- Client/src/Views/Question/Params/FilterParamNew/State.ts
Can be tested on https://wbazant.microbiomedb.org/mbio.wbazant/app/search/sample/SamplesByMetadata_otuDADA2_MALED_healthy_RSRC with an apidb password - some sample details like "SRA Experiment ID" are alternative IDs, and there's over a thousand rows. I acknowledge there's little very point for MicrobiomeDB to show this study while offer those filters, but it's there, and can be used as a test case.
Main rationale of this feature is to make improperly large membership fields usable. This came up for user datasets in MicrobiomeDB and an example input from Earth Microbiome Project, containing thousands of unannotated samples. The UI broke down on this case because rendering of all rows took too long.
Only page if there are over 100 values: there shouldn't usually be this many.
Offer page …
> FilterParamNew: add paging to large membership fields

- Client/src/Controllers/StrategyViewController.tsx
Redirect to root step if id is not valid for existing strategy.
> Redirect to root step if step id is invalid

- Client/src/Components/AttributeFilter/MembershipField.jsx
Fix syntax error that was causing ui state to get lost. Bug report: https://redmine.apidb.org/issues/41341
> Fix syntax error causing table state to get lost.

- Client/src/Actions/StrategyPanelActions.ts
- Client/src/Controllers/StrategyPanelController.tsx
- Client/src/StoreModules/StrategyPanelStoreModule.ts
- Client/src/Views/Strategy/StepBoxes.tsx
- Client/src/Views/Strategy/StrategyPanel.tsx
- Client/src/Views/Strategy/Types.ts
Currently, when we try to "edit" the root of an expanded nested strategy, two step details dialogs open:
1. The associated `NestedStepDetails`
2. The `StepDetails` or `CombineStepDetails` for the nested strategy's root step 
The underlying issue is that... 
1. We are maintaining, via Redux state from the `StrategyPanelStoreModule`, the step id of the `visibleStepDetails`
2. The relation between step ids and step dialogs is not necessarily 1-1. It is 1-2 in the case where the step id is the root of an expanded nested strategy
This PR resolves this issue by moving the step details visibility from Redux state to local component state of each step box. Since there is a 1-1 correspondence between step boxes and step dialogs, this avoids the bug.
Note: I also considered keeping …
> When clicking the "edit" button on a step box, only open one step details dialog

- Client/src/Service/Mixins/UserUploadService.ts
I want the page to wait until the file body is posted, but then transition. But actually, that's not what it does - it transitions sometime between the first request (start upload, sets status as "awaiting upload") and the second. So, it leads to a screen which says "awaiting upload" while still posting the file (which I see for a larger file, when I open a network tab) which is not exactly a bug, but not how I wanted it either - I wanted the "new upload" screen to be at low opacity until the file is posted, and transition afterwards.
The bug scenario is that when the user refreshes the page (and it's very tempting, there's a button to refresh the page, etc.) the upload gets stuck as "awaiting upload" forever: the file does not complete loading, and the server never fails it.
This is …
> Fix bug about order of actions: should first post the file, then transition

- Client/src/Utils/TreeUtils.ts
Use preorder to enumerate all nodes, rather than immediately descending to child nodes.
> Handle tree that contains a single node.

- Client/src/Components/AttributeFilter/Histogram.jsx
This PR fixes an issue where the flot jquery plugin was being invoked numerous times in rapid succession. Due to how the plugin is invoked, it's possible for references to be removed before additional setup is complete. The commit in the PR performs a deep comparison of `uiState` to prevent unnecessary updates.
> Do a deep equality check to prevent unnecessary updates.

- Client/src/Components/DataTable/DataTable.tsx
- Client/src/Utils/DomUtils.ts
- Client/src/Views/Records/RecordUI.jsx
This PR includes fixes that prevent the gene page from jumping around as content is added to the page (sections expanded, images loaded, etc).
This could use some additional testing before being merged. My dev site is currently built with this branch (note that it's configured as a FungiDB website): https://dfalke-b.fungidb.org.
Relevant redmine: https://redmine.apidb.org/issues/41132
> Gene page scroll fix

- Client/src/Actions/QuestionActions.ts
- Client/src/StoreModules/QuestionStoreModule.ts
This PR addresses two reported bugs for the "custom step name" functionality:
1. When adding a step, the "custom name" field on the search page is pre-populated with value from the most recent use of the form. (This is resolved by updating the `customName` whenever the active question changes.)
2. When revising a step, submitting a new "custom name" from the search page does not update the step's custom name. (This is resolved by issuing a step PATCH request. Before, we were just issuing a step PUT request to update the search config.)
> Custom step name fixes

- Client/src/StoreModules/UserDatasetListStoreModule.ts
- Client/src/Views/UserDatasets/List/UserDatasetList.tsx
- Client/src/Views/UserDatasets/UserDatasetStatus.tsx
Opening this as a draft PR so @aurreco-uga can weigh in on the verbiage before it's merged.
This PR introduces two recently suggested UX improvements for the `UserDatasetList`:
1. Don't display the project toggle checkbox unless the user has at least one dataset from another project.
2. Update some of the `UserDatasetStatus` verbiage. (The existing verbiage for the "uploaded but not compatible with this release" case was misleading because `BiomDatasetDetail`s do not have the "compatibility section.")
In addition, a fix is provided for some bugs pertaining to editing details in the `UserDatasetList`. (See https://redmine.apidb.org/issues/40127 and https://redmine.apidb.org/issues/32168.)
**Note:** While this PR fixes the errors that were being thrown on the client, there appears to be …
> User Dataset List: UX enhancements and bugfixes when changing metadata

- Client/src/Hooks/WdkServiceHook.ts
This PR introduces `useWdkServiceWithRefresh`, a variation of the `useWdkService` hook which returns `undefined` before each invocation of the service callback. This can be used to communicate to the invoking component that some kind of spinner/loading indicator should be rendered in-between re-invocations of the service callback.
(The need for this hook arises from a [recent Organism Filter bugfix](https://github.com/VEuPathDB/ApiCommonWebsite/pull/14). There, I refactored `OrganismFilter` to use `useWdkService` instead of `useWdkEffect` / `useState` to fetch/maintain the filter summary data, and needed to some way to tidily encapsulate "clear the organism counts whenever a new step is selected.")
> Introduce "useWdkServiceWithRefresh"

- Client/src/StoreModules/QuestionStoreModule.ts
@dmfalke: If you can think of a more robust solution, and time doesn't permit a dialogue, please do feel free to commit to this PR or open one of your own.
I'd also welcome additional QA from @dmfalke and @aurreco-uga: https://jtlong.plasmodb.org/plasmo.jtlong/app. (Please disregard the unrelated 500 error when the page loads.)
Currently, question form submission errors are handler by this `catch` handler, which is meant to handle all possible rejected promises which might occur in the course of submitting the form:
https://github.com/VEuPathDB/WDKClient/blob/master/Client/src/StoreModules/QuestionStoreModule.ts#L581
In particular, for validation errors, this handler will reenable the "submit" button and display the appropriate validation errors.
[A recent PR of …
> Handle rejected promises which arise as part of question submission

- Client/src/Actions/StrategyActions.ts
- Client/src/StoreModules/QuestionStoreModule.ts
- Client/src/StoreModules/StrategyStoreModule.ts
**Note:** Opening this as a draft PR since the initial implementation needs to be DRYed up before merge.
When submitting a "revise step" form, the latest logic is to dispatch `requestUpdateStepProperties` (to update the customName) and `requestUpdateStepSearchConfig` (to update the searchConfig). This is causing the form to close even if only one of the two updates succeeded.
This PR resolves the issue by introducing a `requestReviseStep` action with an associated `mrate` fulfiller which (1) tries to update the search config and then, if that succeeds, (2) tries to updates the step properties, and then, if both succeed, (3) dispatches the appropriate `fulfillStrategy` actions, or if at least one fails, (4) dispatches a `reportSubmissionError`.
> New "requestReviseStep" action

- Client/src/Controllers/RecordController.tsx
This can happen when going from one record type to another, and is
especially problematic when there is an intermediate non-record-page. In
this case, the initial render will use state from the previous page,
which will cause partial record requests to be made for the previous
record type. Since ownProps and data props are out of sync, requests can
contain fields incompatible with the record type.
> Prevent render when ownProps and data are out-of-sync.

- Client/src/Views/Strategy/StepBoxes.tsx
Opening this as a draft PR so that @aurreco-uga can OK the UX first.
This PR adjusts the UX when the "edit" button of a revisable* invalid step is clicked: when this button is clicked, the Revise Step form modal is opened instead of the Step Details dialog.
\* Here, "revisable" means "can be revised via the Revise Step form modal" (as opposed to "inline" via the Step Details dialog).
> When "edit"ing a (revisable) invalid step, go directly to the Revise Step form

- Client/src/Components/CheckboxTree/CheckboxTree.tsx
- Client/src/Components/CheckboxTree/CheckboxTreeNode.tsx
This PR introduces a new `shouldExpandOnClick` prop for our checkbox tree, which is set to `true` by default.
When `shouldExpandOnClick` is set to `false`, clicking on a node's contents will not trigger an expansion. This behavior is useful for checkbox trees whose nodes have some kind of click-activated controls, such as the "constraint" checkbox trees found in genomics sites' `GenesByOrthologPattern` and OrthoMCL's `GroupsByPhyleticPattern`. In these cases, it is undesirable for nodes to be expanded/collapsed when they are clicked.
(The [current implementation of `GenesByOrthologPattern` circumvents this issue by using stopPropagation](https://github.com/VEuPathDB/ApiCommonWebsite/blob/dadfba80ec2c5303738bb6d1c0caadd6467b396e/Site/webapp/wdkCustomization/js/client/components/questions/Ge …
> Introduce new "shouldExpandOnClick" prop

- Client/src/Actions/AnswerActions.ts
- Client/src/Controllers/AnswerController.tsx
- Client/src/Service/Mixins/OntologiesService.ts
- Client/src/StoreModules/AnswerViewStoreModule.ts
- Client/src/Utils/CategoryUtils.tsx
- Client/src/Views/Answer/Answer.jsx
- Client/src/Views/Answer/AnswerFilter.jsx
- Client/src/Views/Answer/AnswerFilterSelector.jsx
This PR updates the Answer page to read the ontology to determine which attributes and tables to include for the results. It also addresses some performance issues in the Answer page, and adds a convenience function to access the categories ontology.
> Use ontology for Answer page

- Client/src/Actions/QuestionActions.ts
- Client/src/Controllers/LegacyParamController.tsx
- Client/src/Controllers/QuestionController.tsx
- Client/src/Core/Root.tsx
- Client/src/Core/Store.ts
- Client/src/Core/main.js
- Client/src/Core/routes.tsx
- Client/src/Hooks/WdkDependenciesEffect.ts
- Client/src/Service/ServiceBase.ts
- Client/src/Service/WdkService.ts
- Client/src/StoreModules/QuestionStoreModule.ts
- Client/src/StoreModules/UserSessionStoreModule.ts
- Client/src/Utils/Operations.tsx
- Client/src/Utils/ParamValueStore.ts
- Client/src/Utils/StepAnalysisUtils.ts
- Client/src/Utils/WdkModel.ts
- Client/src/Views/Question/DefaultQuestionForm.scss
- Client/src/Views/Question/DefaultQuestionForm.tsx
- Client/src/Views/Question/Params/DatasetParam.tsx
- Client/src/Views/Strategy/CombineStepMenu.tsx
Co-depends on https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/29
This PR... 
1. Introduces a new (IndexedDB-backed) `paramValueStore` WDK Client dependency, which can be used to persist a user's parameter value selections in a variety of contexts.
2. Uses this `paramValueStore` to persist the user's param value choices on search pages. (More precisely, the `QuestionController` now receives an optional `prepopulateWithLastParamValues` prop, which, if enabled, signals that the `paramValueStore` should prepopulate the form with the user's last param value selections for that question.)
**Note:**
The `paramValueStore` is cleared whenever (1) the user logs out or (2) the webapp is reloaded.
> New "Param Value Store" WDK Client Dependency

- Client/src/Controllers/UserCommentShowController.tsx
- Client/src/StoreModules/UserCommentFormStoreModule.ts
- Client/src/Utils/WdkUser.ts
- Client/src/Views/UserCommentShow/UploadedFileRow.tsx
- Client/src/Views/UserCommentShow/UserCommentUploadedFiles.tsx
This PR introduces more robust rendering of User Comment attachment metadata. More specifically, we now offer a preview of a User Comment attachment iff its MIME type is of the form "image/*". (Before, we were only offering this preview if the file's extension was one of three hardcoded types, which was a source of bugs.)
Depends on https://github.com/VEuPathDB/ApiCommonWebsite/pull/19
> User Comment Attachments: don't offer a preview for non-image or unavailable attachments

- Client/src/Utils/Json.ts
As the title suggests, this PR adds two new exports: a decoder for `unknown`, and a `standardErrorReport` function.
> Add decoder for unknown type, and standard error report

- Client/src/Core/MoveAfterRefactor/Components/StepAnalysis/StepAnalysisGoEnrichmentResults.tsx
- Client/src/Core/MoveAfterRefactor/Components/StepAnalysis/StepAnalysisPathwayEnrichmentResults.tsx
This PR addresses https://redmine.apidb.org/issues/42389 by appending a timestamp to the word cloud image url used in the dialog component.
> Append timestamp to image url to break browser cache

- Client/src/Hooks/StateWithHistory.ts
- Client/src/Hooks/__tests__/StateWithHistoryTest.ts
The hook override allows no initial state to be provided, in which case the type is `T | undefined`.
The set function override allows for functional state updates.
> Add overrides for hook and `set` function.

- Client/src/Components/InputControls/wdk-SaveableTextEditor.scss
- Client/src/Views/Strategy/StepBoxes.css
Update styles to prevent content shifting when `SaveableTextEditor` is in edit mode.
> Remove padding, margin, border from input and use outline

- Client/src/Preferences.ts
- Client/src/StoreModules/RecordStoreModule.ts
- Client/src/StoreModules/StrategyWorkspaceStoreModule.ts
- Client/src/Utils/ObserverUtils.ts
This PR introduces a new WDK Preference for the visibility of the record page's navigation tab. As with the existing implementation in genomics sites, it has a `Local` `PersistenceLevel` and is scoped by record type.
Future work:
1. Retire the original implementation in `ApiCommonWebsite`.
2. Make similar WDK Preferences for the other things which are persisted on genomics sites
> New "navigationVisible" Preference

- Client/src/Components/AttributeFilter/Histogram.jsx
- Client/src/Components/AttributeFilter/HistogramField.jsx
- Client/src/Components/AttributeFilter/ServerSideAttributeFilter.jsx
This PR changes the default settings for the histogram view in FilterParam.
* Compute and apply default bin size
* Always include 0 in default xaxis range
* Use log scale for yaxis
* Do not truncate yaxis
The yaxis defaults can be configured using a component override.
refs https://redmine.apidb.org/issues/43098
> Update defaults for histogram, and allow configuration.

- Client/src/Controllers/ResultPanelController.tsx
- Client/src/Core/MoveAfterRefactor/StoreModules/StepAnalysis/StepAnalysisObservers.ts
This PR addresses [this Trello](https://trello.com/c/eu1oPJna/1454-bug-in-step-results-analysis-tab-in-child-step-stays-on-new-boolean) as follows:
1. Step Analysis Redux: after loading a step's analyses, don't update the tab listing if the user has navigated away from the step.
2. Result Panel Controller: if both the previous and current `resultType` are `step`s, don't reload the tabs unless the step id has changed. (Currently, adding a step causes the previous step's tab listing to be reloaded before the client redirects to the new step. This is occurring because the `step`s in the previous and current `resultTypes` are nearly identical, except for their `lastRunTime`s.)
**Note 1:** Only (1) is actually necessary to fix the bug. (2) addresses an unnecessary service call which revealed …
> Result Panel: two related issues around loading step analyses

- Client/src/Service/Mixins/TemporaryFilesService.ts
- Client/src/Service/Mixins/UserUploadService.ts
- Client/src/Service/ServiceBase.ts
- Client/src/Service/ServiceUtils.ts
This PR appends the request url to errors thrown by `fetch` attempts. There are likely other places where we use `fetch`, but this is first pass to improve error reporting.
> Append request url to fetch errors

- Client/src/Controllers/UserDatasetAllUploadsController.tsx
- Client/src/Controllers/UserDatasetListController.tsx
- Client/src/Controllers/UserDatasetNewUploadController.tsx
- Client/src/Core/WdkRoute.tsx
- Client/src/Core/routes.tsx
- Client/src/Views/User/LoginRequiredDisclaimer.tsx
- Client/src/Views/UserDatasets/MicrobiomeDBUploadForm.scss
- Client/src/Views/UserDatasets/MicrobiomeDBUploadForm.tsx
- Client/src/Views/UserDatasets/UserDatasetsWorkspace.tsx
The main point of this PR is to support URLs like
```
https://wbazant.microbiomedb.org/mbio.wbazant/app/workspace/datasets/new?datasetName=Example%20biom&datasetSummary=A%20brief%20summary&datasetDescription=This%20is%20a%20small%20example%20file%20that%20I%20link%20to%20from%20the%20web&datasetUrl=https://raw.githubusercontent.com/biocore/biom-format/master/examples/rich_sparse_otu_table.biom
```
i.e. parameters `datasetName`, `datasetSummary`, `datasetDescription`, `datasetUrl`, so that our collaborators can make them. 
For this change to correctly work, a new handler needs to be deployed: https://github.com/VEuPathDB/dataset-handler-biom/pull/1
and end to end tested. If it doesn't work, 07200c551f53 is the commit that should be undone - the other two are not dependent on this change.
- …
> Path to biom, pre-fill form from URL

- Client/src/Utils/ParamValueStore.ts
This PR addresses is a followup to https://github.com/VEuPathDB/WDKClient/pull/103. It is meant to address the case where the user has changed without a page reload.
For instance:
1. Go the GeneByLocusTag search page and run a search
2. Delete your JSESSIONID cookie
3. Revisit the GeneByLocusTag search page
Currently, this will NOT invalidate the `ParamValueStore`, as the user id is being retrieved using the cached version of `wdkService.getCurrentUser`. The fix is to update the `ParamValueStore`'s `fetchParamValues` method to use the uncached/forced version of `wdkService.getCurrentUser`.
> When fetching param values from the param value store, use the service, not the wdkService cache, to retrieve the current user's id

- Client/package.json
- Client/src/Service/ServiceBase.ts
- Client/src/Utils/FetchWithRetry.ts
This PR introduces a utility to make fetch requests with retry logic: `fetchWithRetry`. The utility accepts a `maxRetry` argument, which is the maximum number of times a fetch operation is retried. A timeout of 250ms is applied before each retry. If the operation fails after the last retry, the error will propagate to the caller, as usual. A custom header (`x-client-retry-count`) is included in each request, which can be useful for backend logging.
The utility is applied the `WdkService` module with a `maxRetry` value of `1`. There are other uses of `window.fetch` which we can apply this utility, but for now we will only apply it to the core `WdkService` fetch logic and monitor `Failed to fetch` errors.
> Fetch with retry

- Client/src/Components/InputControls/Checkbox.tsx
This PR adds `onChange` as a dependency to the `useCallback` which derives the checkbox's `changeHandler`. It is necessary to handle the case where the `onChange` prop is not referentially stable.
(Such as [this reporter form](https://github.com/VEuPathDB/EbrcWebsiteCommon/blob/master/Site/webapp/wdkCustomization/js/client/components/reporters/FastaOrthoSequenceReporterForm.jsx), where the bug was first observed.)
> Checkbox component: add missing "onChange" dependency

- Client/src/Controllers/QuestionController.tsx
- Client/src/Controllers/RecordController.tsx
- Client/src/Utils/ClientPlugin.tsx
- Client/src/Utils/DomUtils.ts
- Client/src/Views/Records/RecordUtils.ts
This PR updates the interface for the client `PluginContext` so that a `paramName` of interest can be provided. In this case, the `parameter` with that specified `paramName` will be included among the `ResolvedReferences` that are passed to client plugin `test` predicates.
In particular, this allows us to consult a parameter's property lists in `test` predicates for plugins of type `questionFormParameter`.
**Note:** In addition, the `stripHTML` utility is moved to a more generic directory, as it will be repurposed in a related `EbrcWebsiteCommon` PR.
**Future work:** Consider making `PluginContext` and `ResolvedReferences` "parametrizable," perhaps based on the `PluginType`.
> Client Plugins: allow paramName context

- Client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts
Spotted happening when a question has an empty ontology, which can be triggered by an action `question/update-params` with an empty `ontology` param, I got it with this action:
```
{
type: 'question/update-params',
payload: {
searchName: 'MicrobiomeSampleByMetadata',
parameters: [
{
displayName: 'Samples',
hideEmptyOntologyNodes: true,
values: {},
sortLeavesBeforeBranches: true,
minSelectedCount: -1,
isVisible: true,
type: 'filter',
countPredictsAnswerCount: true,
help: 'Select reference samples.',
dependentParams: [],
isReadOnly: false,
allowEmptyValue: false,
name: 'samples_filter_metadata_wiz',
initialDisplayValue: '{"filters":[]}',
ontology: [],
group: 'samples_metadata'
}
]
}
}
```
The empty ontology happens during mad clicking around, and makes the UI break. With this change, the …
> Use optional chaining to work around a potential null first()

- Client/src/Views/ReporterForm/WdkServiceJsonReporterForm.tsx
- Client/src/Views/ReporterForm/reporterUtils.tsx
This PR has two bugfixes related to initially selected attributes on download forms:
1. `getAttributeSelections`: fix a logic error that was causing the associated summary user preferences to not be retrieved (the necessary user preference was being looked up at `userPrefs` instead of `userPrefs.project`)
2. `WdkServiceJsonReporterForm`: preselect attributes as in other download forms (currently, no non-primary-key attributes are preselected)
Future [EbrcWebsiteCommon](https://github.com/VEuPathDB/EbrcWebsiteCommon) cleanup: DRY up the existing download forms with the new `getAllReportScopedAttributes` utility.
> Download Form: two bugfixes concerning initially selected attributes

- Client/src/Components/CheckboxTree/CheckboxTree.tsx
- Client/src/Components/CheckboxTree/wdk-CheckboxTree.scss
This PR lets "searchable" `CheckboxTree`s be rendered with "additional" filter controls (that is, filter controls to supplement the default searchbox filter).
**Motivating use case:** enriching a `CheckboxTree` with a toggle filter. 
This new functionality is enabled via two new optional props:
1. `additionalFilters` - an array of `ReactNodes`, each element of which is the display of some filter control. Note in particular that these filter controls are rendered "externally," and as such, the `CheckboxTree` is decoupled from any associated UI state.
2. `isAdditionalFilterApplied` - a boolean flag indicating whether an additional filter has been applied. (This prop is necessary since the `CheckboxTree` is unaware of the UI state for the additional filter controls.)
> CheckboxTree: introduce "additional filters" functionality

- Client/src/Components/AttributeFilter/MembershipField.jsx
This PR allows the prefix used for the table heading for the filtered count column to be configured. It defaults to *Remaining*, so we can try some things out on select sites before making a global change.
> Add prop to configure prefix of filtered heading

- Client/src/Components/CheckboxTree/CheckboxTree.tsx
- Client/src/Views/Question/Params/TreeBoxEnumParam.tsx
This PR moves the rendering logic for the `TreeBoxEnumParam` component into reusable hooks.
Motivating use case: for "organism" params, we want to override a handful of props that are passed to the underlying `CheckboxTree` (most notably `renderNode` and `searchPredicate`).
> Make TreeBoxEnumParam logic reusable

- Client/src/Actions/StrategyActions.ts
- Client/src/Controllers/StrategyPanelController.tsx
- Client/src/StoreModules/StrategyStoreModule.ts
- Client/src/Utils/StrategyUtils.ts
- Client/src/Utils/__tests__/StrategyUtilsTest.ts
- Client/src/Views/Strategy/StepBoxes.tsx
- Client/src/Views/Strategy/StrategyPanel.tsx
- Client/src/Views/Strategy/Types.ts
This PR fixes a bug where, when deleting the root step of a nested strategy, the entire nested strategy is deleted. (See attached image.)
The issue is that roots of nested steps have two associated "step details" dialogs - one displaying a summary of the nested strategy (which can be view by opening details for the "nested control step"), and one displaying the results for the root step itself. For the former, clicking "delete" should delete the entire nested strategy; for the latter, clicking "delete" should delete only the slot with the nested root step. Currently, clicking "delete" on either of these dialogs causes the entire nested strategy to be deleted.
To address this issue, I add, to the `removeStep` utility, an optional `isNestedControlStep` argument. When `true`, this argument …
> When deleting a nested root step, don't delete the other slots of the nested strategy

- Client/src/Views/Records/Record.css
- Client/src/Views/Records/RecordUI.jsx
This PR refactors the `RecordSidebar`'s sticky container to use `position: sticky`.
(Motivation: there is [a Redmine](https://redmine.apidb.org/issues/44483) regarding the new org prefs header blocking the RecordSidebar's header. To fix this, I want to override the position of the sticky container, which is a little easier to do with `position: sticky`.)
> Power the RecordSidebar's sticky container using "position: sticky"

- Client/src/Components.ts
- Client/src/Views/Strategy/SearchInputSelector.tsx
Use case: for Add Step on genomics sites, we want to restrict tree of available searches based on the user's preferred organisms.
> Make SearchInputSelector wrappable

- Client/src/Components.ts
- Client/src/Views/Records/RecordNavigation/RecordNavigationSection.jsx
- Client/src/Views/Records/RecordUtils.ts
This PR allows the `RecordNavigationSection`'s visibility filter to be overridden via a prop.
Use Case: ClinEpi wants to display attributes AND tables in their `RecordNavigationSection`.
@dmfalke I'll be self-merging this since @aurreco-uga wanted to exhibit this work as part of the upcoming ClinEpi UX demo, and I know you're busy with EDA stuff. Please feel free to do a "post-merge review!"
> Configurable Navigation Items

- Client/src/Components/Workspace/WorkspaceNavigation.tsx
- Client/src/Hooks/Page.ts
This PR improves the `WorkspaceNavigation` component in the following ways:
1. Consumers can specify that a "tab" will replace the current location.
2. "Tabs" will set the `scrollToTop` flag to `false` to prevent the page from jumping when switching tabs.
> Workspace navigation: support replace and scrollToTop behavior

- Client/vendored/datatables-natural-type-plugin.js
The semantics of the `html` flag seem the opposite of what is expected. This PR flips the logic.
> Update natural-sort datatables plugin to handle html content as expected

- Client/src/Hooks/NonNullableContext.ts
This is being pulled from https://github.com/VEuPathDB/web-eda/blob/main/src/lib/core/hooks/nonNullableContext.ts. Once this is merged, I can remove it from web-eda and use this version instead.
> Add useNonNullableContext hook

- Client/src/Utils/Task.ts
- Client/src/Utils/__tests__/TaskTest.ts
A `Task`'s underlying process should not be executed until the `.run` method is called. This PR ensures that contract by having `Task.fromPromise` take a callback function.
> Use callback for Task.fromPromise

- Client/src/Components/Mesa/Ui/DataTable.jsx
- Client/src/Controllers/AnswerController.tsx
- Client/src/Core/routes.tsx
- Client/src/Views/Answer/Answer.jsx
This PR improves performance of the Answer table by:
* Introducing client-side pagination to the Answer component
* Speeding up certain rerenders of `Mesa`'s underlying `DataTable` component (by memoizing the derivation of the "columns with dynamic widths")
Avenues for future work:
* Allow Mesa consumers to specify a stabler row key than `rowIndex`.
* Eliminate some/all rerenders of sticky `DataTable`s which occur when their `dynamicWidths` state changes. @dmfalke suggests only passing the dynamic widths to the header of the table.
* Explore other React table libraries.
> Mesa and Answer Table Performance Improvements

- Client/src/Components/Mesa/Ui/DataTable.jsx
- Client/src/Controllers/AnswerController.tsx
- Client/src/Core/routes.tsx
- Client/src/Views/Answer/Answer.jsx
This PR:
* Reverts pagination for the Answer table
* Alters the circumstances where Mesa `DataTable` sticky column widths are recalculated: now instead of recomputing these widths whenever (1) the rows change OR (2) the name and order of the columns changes, we only recompute them in the case of (2). Consequently, sorting or filtering a Mesa table with a sticky header now only triggers one rerender (instead of three).
> Mesa sticky header performance improvement

- Client/src/Controllers/QuestionController.tsx
- Client/src/Controllers/ResultPanelController.tsx
- Client/src/Core/routes.tsx
- Client/src/Utils/ClientPlugin.tsx
- Client/src/Views/Strategy/CombineStepForm.tsx
- Client/src/Views/Strategy/ConvertStepForm.tsx
- Client/src/Views/Strategy/StrategyPanel.tsx
This PR introduces an optional `fallback` prop for client plugins. It is intended to improve loading UX for `Plugin`-based pages/views for which "plugin reference resolution" is delayed.
In addition, fallback are provided for several `Plugin`-based pages/views:
* Search pages
* Question forms in the Add Step and Revise Step modals
* Summary views
* Step analysis views
> Client Plugins: introduce optional "fallback" prop

- Client/src/Components/AttributeFilter/MembershipField.jsx
- Client/src/Components/AttributeFilter/StackedBar.jsx
- Client/src/Views/Question/Params/FilterParamNew/FilterParam.css
*Depends on web-eda [PR #377](https://github.com/VEuPathDB/web-eda/pull/377)*
Addresses web-eda [issue #301](https://github.com/VEuPathDB/web-eda/issues/301)
The goal of this PR is to allow the bar colors in the subsetting step to be optionally defined elsewhere and passed as props. The default values match the current colors on the live site (defined in FilterParam.css, class `.fill.filtered` and `.bar .fill`).
The current PR functions as intended, but I struggled with making the decision about where to define the default colors. Currently this is done in the StackedBar component but other options include within MembershipField or MembershipTable. Is it better to define such a default at the highest or lowest level?
> Add ability to override subsetting distribution bar colors

- Client/src/Components/AttributeFilter/MultiFieldFilter.jsx
With web-eda [PR #408](https://github.com/VEuPathDB/web-eda/pull/408) , allows predefined colors to be passed to the stacked bars in the distribution column of the data table in the subsetting tab, for multifilter variables.
Previous PR #151 updated the above for numeric and categorical variables, but not for multifilter. The same implementation strategy as in PR #151 is implemented here. See also web-eda [issue #301](https://github.com/VEuPathDB/web-eda/issues/301) for more details
> multifilter pass colors to stackedbar

- Client/package.json
- Client/src/Components/AttributeFilter/MembershipField.jsx
This addresses: a) adding volta at package.json; b) add prefix to table heading; c) center alignment for table heading
Following link has screenshots: https://github.com/VEuPathDB/web-eda/issues/418#issuecomment-940517973. 
If this change is accepted by Danica, then I will make this be regular PR.
I noticed that Dave manually makes version up for this WDKClient repo, so it would be necessary to check the version so that it would be upgraded at [corresponding web-eda PR](https://github.com/VEuPathDB/web-eda/pull/551).
> adding prefix at table heading and centered

- Client/src/Core/CommonTypes.ts
- Client/src/Core/Root.tsx
- Client/src/Core/Store.ts
- Client/src/Core/WdkMiddleware.ts
- Client/src/Core/main.js
- Client/src/Hooks/NonNullableContext.ts
- Client/src/Hooks/RefinedContext.ts
- Client/src/Hooks/WdkDependenciesEffect.ts
This PR introduces a `wrapWdkDependencies` config, which can be used to provide additional services to the various consumers of `WdkDependencies`:
1. Component and hooks (via `WdkDependenciesContext`)
2. Redux middleware (passed as an argument to WDK epics and thunks)
A utility hook "factory" is also introduced to facilitate working with wrapped React context.
> Introduce wrapWdkDependencies

- Client/src/Components/InputControls/SaveableTextEditor.tsx
Works toward https://github.com/VEuPathDB/web-eda/issues/653
> Allow any text input or text area attributes in SaveableTextEditor

- Client/package.json
- Client/src/Components/AttributeFilter/AttributeFilterUtils.ts
- Client/src/Components/AttributeFilter/Types.ts
This *almost* works....the only issue is the `GENERATED_ROOT` default. It's type `Field`, and TS complains that `Field` can't be assigned to `T extends Field`. Doing `GENERATED_ROOT as T` works, but is that safe?
> Extension of Field type

- Client/package.json
- Client/src/Views/Answer/Answer.jsx
Addresses [this issue](https://github.com/VEuPathDB/EdaNewIssues/issues/214) wherein removing the column that the summary table is sorted by results in a `TypeError` because `sortingAttribute` is null.
I added a ternary that will pass the first column's name attribute in place of `sortingAttribute` in the event that `sortingAttribute` is null. The first column, study name, is non-removable and thus a safe default.
I tested this small change in both a Plasmo and ClinEpi dev site. Both are exhibiting the desired result.
> Default sort by study when sortingAttribute is null

- Client/package.json
- Client/src/Views/ResultTableSummaryView/ResultTable.tsx
Addresses [this issue](https://trello.com/c/SEN8NY19/1652-results-table-bug-with-paging).
The bug happens when a user changes the "rows per column" such that the `currentPage` would no longer exists. For example, if a user is on page 10 of a study with 500 records set to show 20 rows per column, selecting 100 rows per column would result in only 5 total pages and thus throw an error (since page 10 no longer exists).
I added a check in the `onRowsPerChange` handler that sets the `currentPage` to the last available page in the event this happens.
> Fix results table bug when rows per page are increased

- Client/package.json
- Client/src/Views/Question/DefaultQuestionForm.tsx
- Client/src/Views/Question/Params/Utils.ts
Relates to https://github.com/VEuPathDB/web-multi-blast/issues/10. That issue is likely arising because users can submit 
a "new job" form while its advanced parameters are being refreshed. In MultiBLAST, such submission errors are not immediately caught, because the WDK doesn't (and likely can't) validate "new job" form submissions.
> Search pages: disable form submission while dependent params are updating

- Client/package.json
- Client/src/Service/Mixins/SearchReportsService.ts
- Client/src/Views/ResultTableSummaryView/ResultTable.tsx
Relates to #209
This PR introduces two small enhancements to accommodate Gene List UD exports:
1. The `getTemporaryResultPath` WdkService method is updated to allow step id inputs
2. The `ResultTable` is given an optional `renderToolbarContent` prop. In particular, this allows custom export option(s) to be displayed, and/or the default buttons to be displayed in a custom way. [Example use of the former](https://github.com/VEuPathDB/ApiCommonWebsite/blob/7b362f928bfbd945dec5ec0dc6ab2f1a88e26947/Site/webapp/wdkCustomization/js/client/components/records/TranscriptRecordClasses.TranscriptRecordClass.jsx#L89-L140).
(Something to consider now or in the near future: is "custom export option(s)" a common enough use case to warrant a special `customExports` prop?)
> Accommodate Gene List UD exports

- Client/package.json
- Client/src/Components/Icon/HelpIcon.tsx
The `HelpIcon` tooltip component used in the screenshot below did not allow a user to interact with the link. Adding the `interactive` [attribute to the React Tooltip component](https://v4.mui.com/components/tooltips/#interactive) fixes this issue.
> Add interactive attribute to HelpIcon tooltip

- Client/package.json
- Client/src/Components/Mesa/Ui/TableToolbar.jsx
While working [to add a counter](https://github.com/VEuPathDB/ApiCommonWebsite/issues/72) in an `ApiCommonWebsite` component, I noticed the pluralization seemed off in the counter.
The existing line `const noun = (isSearching ? 'result' : 'row') + (count % rowsPerPage === 1 ? '' : 's');` results in a singular noun when the count is 16 and the rowsPerPage are 5, yet there are multiple rows being displayed.
I replaced the modulo condition with `count - filteredRowCount === 1` which seemed to consistently provide the pluralization I was expecting.
> Tweak pluralisation logic in TableToolbar counter

- Client/package.json
- Client/src/Views/Records/RecordAttributes/RecordAttributeSection.tsx
This is to support the new alphafold visualization. It is currently implemented as a record attribute. We want it to be in a collapsible section.
> Export InlineRecordAttributeSection and BlockRecordAttributeSection 

- Client/package.json
- Client/src/Views/ResultTableSummaryView/ResultTable.tsx
Together with [this work in ApiCommonWebsite](https://github.com/VEuPathDB/ApiCommonWebsite/pull/86), this addresses a paging error when the global view filter changes ([Redmine #48424](https://redmine.apidb.org/issues/48424)).
> Use meta.viewTotalCount for pagination to account for filtering

- Client/package.json
- Client/src/Views/Records/RecordAttributes/RecordAttribute.jsx
- Client/src/Views/Records/RecordAttributes/RecordAttributeSection.tsx
Previously, we were hiding such attributes completely. With the change to show all attributes in the TOC, it makes more sense to include them on the page.
> display empty attributes on record page, with indication that no data is available

- Client/package.json
- Client/src/Views/ResultTableSummaryView/AttributeCell.tsx
This PR uses a more robust method for truncating text of textAttributes in the result table summary view. The previous method was causing invalid HTML to be inserted into the DOM by React, which was rendering the cell empty.
> Handle truncation via CSS

- Client/package.json
- Client/src/Views/Question/Params/FilterParamNew/FilterParam.css
- Client/src/Views/Records/Record.css
Fixes [ issue](https://github.com/VEuPathDB/ApiCommonWebsite/issues/90)
Also went ahead and reverted the `CheckboxTree` in the record navigation sidebar to use `overflow-y: auto` since `overflow-y: scroll` resulted in a permanent scrollbar, either in an enabled or disabled state.
> Fix dimension error in Genetic variation plot and set overflow-y: auto

- Client/package.json
- Client/src/Actions/UserActions.ts
- Client/src/Service/Mixins/UsersService.ts
- Client/src/Views/User/UserFormContainer.jsx
Solution as discussed in scrum.  I think everything is working as expected coupling these changes with [a back-end fix](https://github.com/VEuPathDB/WDK/commit/6458ca290a36422a72b3d452f2834f014ce879cf) to update the user object on the session after update.  Together, these should address:
1. User object being cached in back-end session is not updated during profile updates
2. User trying to reset email to email assigned to existing account gets bad message (client mishandles 409)
3. After 409 occurs, currentUser promise is broken and can only be fixed with a getCurrentUser({force:true})
4. User successfully updating email address, user gets logged out (race condition between profile update and prefs update)
Note: after approval, this commit should be added to the live sites.
> Refine user promise cache management + fix tag nesting warning

- Client/package.json
- Client/src/Views/ResultTableSummaryView/ResultTableAddColumnsDialog.tsx
Resolves #246
Follow up work that improves the UI of the modal will be handled when replacing the existing WDKClient `CheckboxTree` with the new version from CoreUI, as outlined in #248.
> Limit columns added to strategies panel table

- Client/package.json
- Client/src/Utils/ComponentUtils.tsx
This fixes cases where a `null` value is passed in, such as the gene page's transcriptomics table.
> Handle null value for `str` parameter

- Client/package.json
- Client/src/Views/ResultTableSummaryView/AttributeCell.tsx
Resolves #260 
Added some logic to prevent `Tooltip` from rendering in cells that exceed the truncation limit but don't overflow the `maxWidth`.
> Refactor how AttributeCell handles truncation

- Client/package.json
- Client/src/Components/DataTable/DataTable.tsx
- Client/src/Components/SearchBox/RealTimeSearchBox.tsx
- Client/yarn.lock
Resolves [this Redmine request](https://redmine.apidb.org/issues/40708).
Uses the [search() method](https://datatables.net/reference/api/search()) from the jQuery `DataTable`'s API.
**Note**: The background when hovering `select all` and `clear all` will be removed via https://github.com/VEuPathDB/CoreUI/pull/130
> Wire up column filters in record tables

- Client/package.json
- Client/src/Components/AttributeFilter/Histogram.jsx
Maybe resolves: #270. Feedback, please!
| Before | After |
|---|---|
| ![Before](https://user-images.githubusercontent.com/24446573/212404408-758dc07a-b859-4046-b8f3-d84256fa8908.png) | ![After](https://user-images.githubusercontent.com/24446573/212404786-124f3196-b9c6-4796-a003-629959378d99.png) |
**Notes**:
- This resolves the default value that the viz is loaded with. Users are free to change use decimals if they want.
- I don't know if there are any tests covering this.
- I also may have overlooked one or many things in my newness.
**Questions**:
- Do we use any code formatting tools?
- What does testing look like? How can I know how many bugs I just introduced with my change? 😏
>  confine bin width to int when all values are ints

- Client/package.json
- Client/src/Service/Mixins/SearchReportsService.ts
- Client/src/Service/Mixins/StepsService.ts
- Client/src/Utils/WdkModel.ts
**Before:**
**After**:
Companion PR: https://github.com/VEuPathDB/web-app-preferred-organisms/pull/9
> Add bufferEntireResponse flag where needed

- Client/package.json
- Client/src/Components/AttributeFilter/FieldList.jsx
- Client/src/Components/AttributeFilter/ServerSideAttributeFilter.jsx
- Client/src/Views/Question/Params/FilterParamNew/FilterParam.css
Resolves `Redmine #50182 - gene page: isolate alignments: filterParam: selecting a variable jumps page to top`
I fear this may be too simplistic. I've removed the logic from `FieldNode` that adjusts page position because it doesn't seem appropriate in the gene records context. Doing so fixed the jump to the top of the page.
> Fix break in scrolling logic from CSS changes to FieldList's FieldNode component

- Client/package.json
- Client/src/Views/Question/Params/SelectionInfo.tsx
Accompanies https://github.com/VEuPathDB/web-app-preferred-organisms/pull/12 in order to better reflect components that are limited to one selection.
Before:
After:
- _**see below for updated screenshot**_
> Amend SelectionInfo message for when maxSelectedCount is 1

- Client/package.json
- Client/src/Controllers/QuestionController.tsx
Resolves https://redmine.apidb.org/issues/47596 which asks to change the reset button's verbiage in the question forms.
Before:
After:
> Amend reset btn verbiage in question forms

- Client/package.json
- Client/src/Components/Layout/Page.tsx
- Client/src/Core/Root.tsx
- Client/src/Core/RouteEntry.tsx
- Client/src/Core/Style/wdk-Common.scss
This PR allows a route to declare that it is fullscreen. This will cause the header and footer to not be rendered. It will also remove any padding from the `PageContent` container.
> Add fullscreen routes

- Client/package.json
- Client/src/Service/Mixins/LoginService.ts
- Client/src/Service/Mixins/StepAnalysisService.ts
- Client/src/Service/Mixins/TemporaryFilesService.ts
- Client/src/Service/ServiceBase.ts
- Client/src/Service/ServiceUtils.ts
This PR adds a `traceid` header to requests made to the WDK service.
> Add traceid header to requests

- Client/package.json
- Client/src/Components/Mesa/Ui/DataTable.jsx
- Client/src/Components/Mesa/style/Vars.scss
- Client/src/Views/ResultTableSummaryView/AttributeCell.tsx
- Client/src/Views/ResultTableSummaryView/ResultTableSummaryView.scss
Resolves https://github.com/VEuPathDB/WDKClient/issues/285
It seems the `useIsRefOverflowingHorizontally` gets out of sync and thus its use as a condition in the truncation logic is problematic. Removing it seems to behave as desired, leaving only this check to determine truncation:
```js
if (
ref.current.innerText.length > attribute.truncateTo &&
isEqual(styleSpec, defaultStyleSpec) 
)
```
> Resolve still-present column overflow issues

- Client/package.json
- Client/vendored/datatables.js
- Client/vendored/datatables.min.js
This fixes an issue where a third party dependency creates a global `exports` object, breaking the feature detection used by these scripts, to determine if they are being run in a CommonJS environment.
> Ensure `exports` is not defined when loading datatables script
