VEuPathDB/WDKClient

- Client/src/Service/Decoders/RecordClassDecoders.ts
- Client/src/Service/Mixins/SearchesService.ts
- Client/src/Service/ServiceBase.ts
- Client/src/Utils/WdkModel.ts
If we get a question from the cache which says it's uncacheable, do not use it
Requires https://github.com/VEuPathDB/WDK/commit/92a4795fd0
> Fix for user dataset questions that shouldn't be cached

- Client/src/Components/Layout/Page.tsx
This PR exposes the Props type for the Page component, which is needed for the implementation of the associated OrthoMCLPage wrapper.
> New ortho layout

- Client/src/Actions/UnhandledErrorActions.ts
- Client/src/Views/UnhandledErrors/UnhandledErrors.scss
- Client/src/Views/UnhandledErrors/UnhandledErrors.tsx
Some updates to verbiage and layout
> Client error verbiage update

- Client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts
This PR contains a bugfix for https://redmine.apidb.org/issues/41453.
> Check reload counts of invalid flag is set

- Client/src/Views/Question/Params/TreeBoxEnumParam.tsx
Bug fix for https://redmine.apidb.org/issues/41282
> Ensure root node is never selected, and some cleanup.

- Client/src/Views/Answer/Answer.jsx
client : sorting a column type number, per convo with dave
> refs 41641

- Client/src/Views/AttributeAnalysis/HistogramAnalysis/HistogramAnalysis.tsx
- Client/src/Views/AttributeAnalysis/HistogramAnalysis/HistogramAnalysisUtils.ts
This PR fixes https://redmine.apidb.org/issues/41679.
> ensure bin sizes are positive

- Client/src/Utils/UserPreferencesUtils.ts
See https://trello.com/c/9uiYZQok/1363-jason-user-preferences-issue
> Use default sorting from question if error when parsing.

- Client/src/Components/AttributeFilter/Histogram.jsx
Fixes https://redmine.apidb.org/issues/42036
> Remove unnecessary properties from check.

- Client/src/Components/Overlays/Modal/Modal.scss
- Client/src/Utils/IterableUtils.ts
- Client/src/Views/UnhandledErrors/UnhandledErrors.scss
- Client/src/Views/UnhandledErrors/UnhandledErrors.tsx
- README.md
This PR updates the layout of the modal. Errors are grouped by message and some font sizes have changed. Stack traces are also no longer displayed in the browser. They are still available in the developer console.
> Error modal updates

- Client/package.json
- Client/src/Hooks/StateWithHistory.ts
- Client/src/Hooks/__tests__/StateWithHistoryTest.ts
- Client/yarn.lock
This PR includes
* The addition of testing libraries for React hooks.
* A `useStateWithHistory` hook and associated tests.
> State with history hook

- Client/src/StoreModules/StrategyWorkspaceStoreModule.ts
This PR addresses https://redmine.apidb.org/issues/42669
> Clear out strategySummaries when view is opened, in case it is stale.

- Client/src/Utils/Json.ts
Adds generic catcall overrides for combinators.
> Add catchall overrides

- Client/src/Hooks/StateWithHistory.ts
- Client/src/Utils/CategoryUtils.tsx
This PR includes some changes to support the EDA Workspace:
1. Updated `useStateWithHistory`
2. Export `getScopes` in `CategoryUtils.tsx`
> Eda workspace related updated

- Client/src/Actions/SummaryView/BlastSummaryViewActions.ts
- Client/src/Actions/SummaryView/GenomeSummaryViewActions.ts
- Client/src/Actions/SummaryView/ResultTableSummaryViewActions.ts
- Client/src/Components/PageStatus/ContentError.tsx
- Client/src/Controllers/BlastSummaryViewController.tsx
- Client/src/Controllers/GenomeSummaryViewController.tsx
- Client/src/Controllers/ResultTableSummaryViewController.tsx
- Client/src/Service/ServiceBase.ts
- Client/src/StoreModules/BlastSummaryViewStoreModule.ts
- Client/src/StoreModules/GenomeSummaryViewStoreModule.ts
- Client/src/StoreModules/ResultTableSummaryViewStoreModule.ts
Handle response errors for summary view reports, and show error message in result panel.
> Handle summary view errors

- Client/src/StoreModules/QuestionStoreModule.ts
Needed in the wizard as the unfiltered count
> Add a __total__ groupUIState and check when to load it

- Client/src/Components/CheckboxTree/CheckboxTree.tsx
This is useful to add UI elements to the CheckboxTree component.
> Add prop to wrap the tree section of CheckboxTree

- Client/src/Components/AttributeFilter/MembershipField.jsx
See https://github.com/VEuPathDB/web-eda/issues/28
> Avoid duplicated categories in table filter when clicking "check all"

- Client/src/Views/Question/Params/EnumParamUtils.ts
This PR allows any param value to be passed to `toMultiValueArray`, not just an enum JSON string. If the passed param value is not such a string, an array consisting of just the param value is returned.
> Update "toMultiValueArray" to allow values of both single-pick and multi-pick enum params

- Client/package.json
- Client/yarn.lock
Hoping this will help w/ resolving runtime issues seen on qa.clinepidb.org
> Upgrade components

- Client/package.json
- Client/src/Service/Mixins/SearchReportsService.ts
This is needed for the "Send to Galaxy" feature
> Add function to get path to a temporary WDK result

- Client/package.json
- Client/src/Service/Mixins/LoginService.ts
- Client/src/StoreModules/UserSessionStoreModule.ts
This PR accommodates login/logout functionality for "external" web clients (such as, purely hypothetically, locally run dev servers 😉).
> External Client Login

- Client/package.json
- Client/src/Components/CheckboxTree/CheckboxTree.tsx
Works toward https://github.com/VEuPathDB/web-eda/issues/838
> Add missing prop dependency to CheckboxTree isLeafVisible function

- Client/package.json
- Client/src/Hooks/LocalBackedState.ts
- Client/src/Hooks/SessionBackedState.ts
- Client/src/Hooks/StorageBackedState.ts
Modeled after [useSessionBackedState](https://github.com/VEuPathDB/WDKClient/blob/master/Client/src/Hooks/SessionBackedState.ts) hook.
Created initially for [this issue](https://github.com/VEuPathDB/web-eda/runs/5486055242?check_suite_focus=true) related to the performance warning for 3 large datasets.
> Create useLocalStorageState hook

- Client/package.json
Use latest version of `@veupathdb/components`
> Peer dep components

- Client/package.json
- Client/src/Components/Shared/ResetFormButton.tsx
- Client/src/Controllers/QuestionController.tsx
- Client/src/Views/Question/DefaultQuestionForm.scss
- Client/src/Views/Question/DefaultQuestionForm.tsx
Exported the `ResetFormButton` component in order to use it in `SrtForm` as part of [this work](https://github.com/VEuPathDB/ApiCommonWebsite/pull/59).
> Export ResetFormButton component

- Client/package.json
- Client/src/Actions/QuestionActions.ts
- Client/src/Controllers/QuestionController.tsx
- Client/src/Core/routes.tsx
- Client/src/StoreModules/QuestionStoreModule.ts
> Search pages: allow new strategies to be given a custom name

- Client/package.json
- Client/src/Actions.ts
- Client/src/Actions/BasketActions.ts
- Client/src/Actions/NotificationActions.ts
- Client/src/Actions/StrategyWorkspaceActions.ts
- Client/src/Components/Notifications.tsx
- Client/src/Controllers/StrategyWorkspaceController.tsx
- Client/src/StoreModules.ts
- Client/src/StoreModules/BasketStoreModule.ts
- Client/src/StoreModules/NotificationStoreModule.ts
- Client/src/StoreModules/StrategyWorkspaceStoreModule.ts
- Client/src/Views/Strategy/StrategyNotifications.tsx
- Client/yarn.lock
Resolves #215; also introduces some infrastructure to allow snackbar notifications to be displayed in response to redux actions
Depends on https://github.com/VEuPathDB/CoreUI/pull/71
Can be tested using [this PR](https://github.com/VEuPathDB/ApiCommonWebsite/pull/61)'s branch
> Snackbar Notifications for Strategy Workspace

- Client/package.json
- Client/src/Views/Records/RecordNavigation/RecordNavigationSection.jsx
fixes #230
The PR add _all_ attributes to the record page navigation section.
> show all fields in the record page navigation panel

- Client/package.json
- Client/src/Components/InputControls/wdk-SaveableTextEditor.scss
> SaveableTextEditor: don't constrain the width of the "edit" icon

- Client/package.json
- Client/src/Views/Records/RecordNavigation/RecordNavigationItem.jsx
- Client/src/Views/Records/RecordUI.jsx
> Record Page: when jumping to a collapsed section, automatically open it

- Client/package.json
- Client/src/Components/DataTable/DataTable.tsx
- Client/src/Views/Records/RecordTable/RecordTable.jsx
Needed as part of VEuPathDB/ApiCommonWebsite#82
> Record Table: onDraw prop; external control of Record Table search term

- Client/package.json
- Client/src/Views/Question/Params/FilterParamNew/FilterParam.css
Resolves [ApiCommonWebsite#90](https://github.com/VEuPathDB/ApiCommonWebsite/issues/90).
Of note, I also added horizontal scrolling to the `Plot Settings` container since it felt very broken as the screen was reduced. Obviously, the page is not designed for small screen widths, but it overflows rather quickly upon reduction so I decided to address it.
> Adjust CSS in FilterParam

- Client/package.json
- Client/src/Components/AttributeFilter/MultiFieldFilter.jsx
Fixes #255 
Also remove unnecessary use of `Seq`.
> Display a better message if multifilter has no data.

- Client/package.json
- Client/src/Components/Layout/Page.tsx
- Client/src/Controllers/UnhandledErrorsController.tsx
- Client/src/Core/Root.tsx
- Client/src/Core/main.js
- Client/src/Views/UnhandledErrors/UnhandledErrors.tsx
Supports https://github.com/VEuPathDB/EbrcWebsiteCommon/issues/172
This PR adds support for require a user to login to access a website.
> Add support for required login

- Client/package.json
- Client/src/Components/Tabs/Tabs.scss
- Client/src/Views/Question/DefaultQuestionForm.scss
- Client/src/Views/Question/DefaultQuestionForm.tsx
Resolves https://github.com/VEuPathDB/WDKClient/issues/278
Depends on https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/201
Further supported by https://github.com/VEuPathDB/ApiCommonWebsite/pull/142
> Wire up tabs in search pages
